[package]
name = "phage_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "*"
bit-vec = { version = "0.6", features = ["serde"] }
rayon = "1.5.3"
clap = "*"
rand = "*"
rustc-hash = "1.1.0"
serde = "1.0.147"
serde_json = "1.0.87"
