PhageFilter:
  database_name: "tree_10010"
  kmer_size: 10
  theta: 0.4
Kraken2:
  database_name: "krakenDB/"
  kmer_size: 35
  minimizer_len: 31
  minimizer_spacing: 0
FastViromeExplorer:
  database_name: "fve_db.idx"
  kmer_size: 31
  tool_path: "FastViromeExplorer/"
  list_file_path: "ncbi-viruses-list.txt"
FACS:
  database_name: "facs_bloom"
  kmer_size: 10
  theta: 0.3
BioBloomTools:
  database_name: "bbt_bloom"
  kmer_size: 10
Clark:
  database_name: "clarkDB/"
  kmer_size: 31
  tool_path: "benchmarking/CLARKSCV1.2.6.1/exe/CLARK"