name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Rust
              uses: actions/setup-rust@v2

            - name: Install Tarpaulin
              run: sudo apt-get install -y cmake libssl-dev pkg-config
            - run: cargo install cargo-tarpaulin

            - name: Run Tests
              run: cargo +nightly tarpaulin --out Xml

            - name: Upload coverage report
              uses: actions/upload-artifact@v2
              with:
                  name: coverage-report
                  path: target/debug/coverage/
            - name: Update README.md
              uses: peaceiris/actions-readme@v2.3.3
              with:
                template: badges
                data: |
                  {
                    "tarpaulin": [
                      {
                        "name": "Coverage",
                        "value": "${{fromJson(steps.read_coverage_file.outputs.coverage).tarpaulin[0].line_coverage.total}}%",
                        "color": "green"
                      }
                    ]
                  }

              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              needs: test
              steps:
                - name: Read coverage file
                  id: read_coverage_file
                  run: echo "::set-output name=coverage::$(node -p 'JSON.stringify({coverage: require(process.env.GITHUB_WORKSPACE + "/target/debug/coverage/coverage.json")})')"
                - name: Setup Node.js
                  uses: actions/setup-node@v2
                  with:
                    node-version: "14"
                - name: Install @actions/toolkit
                  run: npm install @actions/toolkit