name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Rust
              uses: actions/setup-rust@v2

            - name: Install Tarpaulin
              run: sudo apt-get install -y cmake libssl-dev pkg-config
            - run: cargo install cargo-tarpaulin

            - name: Run Tests
              run: cargo +nightly tarpaulin --out Xml

            - name: Upload coverage report
              uses: actions/upload-artifact@v2
              with:
                  name: coverage-report
                  path: target/debug/coverage/
            - name: Update README.md
              uses: peaceiris/actions-readme@v2.3.3
              with:
                  template: badges
                  data: |
                      {
                        "tarpaulin": [
                          {
                            "name": "Coverage",
                            "value": "${{fromJson(readFileSync('./target/debug/coverage/coverage.json').toString())['tarpaulin'][0]['line_coverage']['total']}}%",
                            "color": "green"
                          }
                        ]
                      }
